#if !canImport(ObjectiveC)
import XCTest

extension DangerSwiftTestingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DangerSwiftTestingTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DangerSwiftTestingTests.__allTests__DangerSwiftTestingTests),
    ]
}
#endif
