language: generic
sudo: false
dist: trusty

stages:
- test
- name: danger
  if: type = pull_request

os: osx
osx_image: xcode10.2

jobs:
  include:
  - stage: test
  - script: swift run danger-swift ci
    install:
    - npm install -g danger
    - swift build
    stage: danger

cache:
directories:
# General SwiftPM
# Danger Swift plugins, like Yams
- .build
- ~/.danger-swift

script:
- swift test
