name: Danger

on: pull_request

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest]
    runs-on: ${{ matrix.os }}
    name: Test
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: swift test
  danger:
    name: Run Danger
    needs: test
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Danger JS
      run: npm install -g danger
    - name: Build danger-swift
      run: swift build
    - name: Run Danger
      run: swift run danger-swift ci
