name: Danger

on: pull_request

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest]
    runs-on: ${{ matrix.os }}
    name: Test
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: swift test
  danger:
    name: Run Danger
    needs: test
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: danger/swift@2.0.1
