name: CI

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [macOS-latest]
    runs-on: ${{ matrix.os }}
    name: Test
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: swift test 1>/dev/null
